server:
  listen-port: 8080

database:
  host: localhost
  port: 5432
  database: medias_dev
  user: medias_user
  ssl-mode: disable

s3:
  region: eu-central-1
  endpoint: http://localhost:9000
  public-endpoint: http://localhost:9000
  bucket-name: medias-dev
